input {
  # 정기 스케줄링 실행용
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/lib/mysql-connector-j-8.0.33.jar"
    jdbc_driver_class => "com.mysql.cj.jdbc.Driver"
    jdbc_connection_string => "${MYSQL_URL}"
    jdbc_user => "${MYSQL_USER}"
    jdbc_password => "${MYSQL_PASSWORD}"
    schedule => "5 8-18/2 * * 1-5"  # 평일 오전9시~오후7시, 2시간마다 실행
    lowercase_column_names => false
    
    statement => "
SELECT 
  p.product_id   AS productId,
  p.product_name AS productName,
  p.price,
  p.product_image AS imageUrl,
  p.manufacturer AS manufacturer,
  c.category_id  AS categoryId,
  c.category_name AS categoryName,
  pc.category_id AS parentCategoryId,
  pc.category_name AS parentCategoryName
FROM products p
LEFT JOIN category c ON p.category_id = c.category_id
LEFT JOIN category pc ON c.parent_id = pc.category_id
    "
  }
  
  # 즉시 실행용 (초기 로딩, 재시작시 실행)
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/lib/mysql-connector-j-8.0.33.jar"
    jdbc_driver_class => "com.mysql.cj.jdbc.Driver"
    jdbc_connection_string => "${MYSQL_URL}"
    jdbc_user => "${MYSQL_USER}"
    jdbc_password => "${MYSQL_PASSWORD}"
    # 스케줄 없음 - 시작시 즉시 한번 실행
    lowercase_column_names => false
    
    statement => "
SELECT 
  p.product_id   AS productId,
  p.product_name AS productName,
  p.price,
  p.product_image AS imageUrl,
  p.manufacturer AS manufacturer,
  c.category_id  AS categoryId,
  c.category_name AS categoryName,
  pc.category_id AS parentCategoryId,
  pc.category_name AS parentCategoryName
FROM products p
LEFT JOIN category c ON p.category_id = c.category_id
LEFT JOIN category pc ON c.parent_id = pc.category_id
    "
  }
}

filter {
  if [parentCategoryId] {
    mutate {
      add_field => { "childCategoryId" => "%{categoryId}" }
      replace => { "categoryId" => "%{parentCategoryId}" }
      replace => { "categoryName" => "%{parentCategoryName}" }
    }
  } else {
    mutate {
      add_field => { "childCategoryId" => "%{categoryId}" }
    }
  }
}

output {
  stdout { codec => rubydebug }

  elasticsearch {
    hosts => ["${ELASTICSEARCH_HOSTS}"]
    ssl => false
    user => "${ELASTICSEARCH_USER}"
    password => "${ELASTICSEARCH_PASSWORD}"
    index => "products"
    document_id => "%{productId}"
    action => "index"
    codec => json
  }
}