input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/lib/mysql-connector-j-8.0.33.jar"
    jdbc_driver_class => "com.mysql.cj.jdbc.Driver"
    jdbc_connection_string => "${MYSQL_URL}"

    jdbc_user => "${MYSQL_USER}"
    jdbc_password => "${MYSQL_PASSWORD}"
    schedule => "* 9-18 * * 1-5"  # 평일(월~금) 오전 9시~오후 5시, 매 시간 정각에 실행
    lowercase_column_names => false

    statement => "
SELECT 
  p.product_id   AS productId,
  p.product_name AS productName,
  p.price,
  p.product_image AS imageUrl,
  p.manufacturer AS manufacturer,
  c.category_id  AS categoryId,
  c.category_name AS categoryName,
  pc.category_id AS parentCategoryId,
  pc.category_name AS parentCategoryName
FROM products p
LEFT JOIN category c ON p.category_id = c.category_id
LEFT JOIN category pc ON c.parent_id = pc.category_id
    "
  }
}

filter {
  if [parentCategoryId] {
    mutate {
      add_field => { "childCategoryId" => "%{categoryId}" }
      replace => { "categoryId" => "%{parentCategoryId}" }
      replace => { "categoryName" => "%{parentCategoryName}" }
    }
  } else {
    mutate {
      add_field => { "childCategoryId" => "%{categoryId}" }
    }
  }
}

output {
  stdout { codec => rubydebug }

  elasticsearch {
    hosts => ["${ELASTICSEARCH_HOSTS}"]
    ssl => false
    user => "${ELASTICSEARCH_USER}"
    password => "${ELASTICSEARCH_PASSWORD}"
    index => "products"
    document_id => "%{productId}"
    action => "index"
    codec => json
  }
}