server:
  port: 8761  # Eureka 서버가 실행될 포트 번호 (표준 Eureka 포트)

spring:
  application:
    name: eureka  # 이 애플리케이션의 이름 설정

eureka:
  client:
    register-with-eureka: false  # 자기 자신을 Eureka 서버에 등록하지 않음 (서버 자체이므로)
    fetch-registry: false  # 다른 서비스 목록을 가져오지 않음 (서버 자체이므로)
  server:
    enable-self-preservation: false  # 자기 보존 모드 비활성화 (개발 환경에 적합, 프로덕션에서는 true 권장)